Feature/GitHub actions publisher
carbynestack/.github pull request #1
Opened 2022-06-30 14:15 UTC by jaredweinfurtner

From Issue:  [#22](https://github.com/carbynestack/carbynestack/issues/22)

2022-07-01 06:15 UTC, strieflin requested changes

2022-07-01 06:15 UTC, strieflin commented on .github/workflows/github-actions-publisher.yaml
> +name: Organizational Github Actions Publisher
License header is missing

2022-07-01 06:15 UTC, strieflin commented on .github/workflows/github-actions-publisher.yaml
> +          github_token: ${{ secrets.CS_MINION_PAT }}
Newline at end of file missing

2022-07-01 06:15 UTC, strieflin commented on templates/workflows/stale-issue-pr-closer.yaml
> +name: 'Close Stale Issues and PRs'
License header missing

2022-07-01 06:15 UTC, strieflin commented on templates/workflows/stale-issue-pr-closer.yaml
> +
That emptyline can be removed

2022-07-01 06:15 UTC, strieflin commented on .github/workflows/github-actions-publisher.yaml
> +          git commit -m "Updating GitHub Actions from the origanization .github repo"
Is it possible to have that commit signed ("-sS" option)?

2022-08-05 13:56 UTC, sbckr commented
@jaredweinfurtner How about using [reusable workflows](https://github.blog/2022-02-10-using-reusable-workflows-github-actions/) instead of pushing the workflow into all other repositories?

2022-11-16 15:27 UTC, jaredweinfurtner commented
Removing Pull Request due to alternative approach as suggested by @sbckr

2022-11-16 15:27 UTC, closed without merging